# Configuração geral da aplicação
spring.application.name=neohorizon

# Configurações de acesso ao banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_DATABASE}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Caminho do arquivo de variáveis de ambiente
.env_FILE=./.env

# Configurações do Swagger para documentação da API
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/api-docs

# Configurações do usuário ETL (service account)
app.etl.email=${ETL_EMAIL}
app.etl.password=${ETL_PASSWORD}

# Configurações do usuário ADMIN (service account)
app.admin.email=${ADMIN_EMAIL}
app.admin.password=${ADMIN_PASSWORD}

# Configurações do usuário DEV (service account)
app.dev.email=${DEV_EMAIL}
app.dev.password=${DEV_PASSWORD}

# Configurações do usuário MANAGER (service account)
app.manager.email=${MANAGER_EMAIL}
app.manager.password=${MANAGER_PASSWORD}